{% set name = "kitemviews" %}
{% set version = "5.79.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kitemviews-{{ version }}.tar.xz
  sha256: d4022ec9599e5b99c6c3e11e1145e6f85d1a87a0d57d9a42aec24605bb87415c

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kitemviews', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5ItemViews.so

about:
  home: https://api.kde.org/frameworks/kitemviews/html/index.html
  license: GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later
  license_file:
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
  summary: Set of item views extending the Qt model-view framework
  description: |
    KItemViews includes a set of views, which can be used with item models.
    It includes views for categorizing lists and to add search filters to
    flat and hierarchical lists.
  dev_url: https://cgit.kde.org/kitemviews.git/tree

extra:
  recipe-maintainers:
    - scopatz
